### ISSUE TITLE
Same 4 fortunes returning on refresh

### ISSUE THREAD

**Issue by susangreve** [susangreve/fortune-cookie-api#13]
Refreshed browser 5 times, same 4 fortunes returned despite having X number of fortunes to draw from. Fortunes endpoint returning same 4 fortunes in random order.

**expected result**
- new fortune should return on each refresh

**observed result**
- same 4 fortunes returned

steps to replicate : 
1. go to fortune-cookie-monster.herokuapp.com/api/fortune/
2. observe fortune
3. refresh browser at least 4 times

**Comment by dmiddlecamp** [comment]
title: fortune page not really random.

**observed:**

```
{"ok":false,"message":"\"... the educated person is not the person who can answer the questions, but\nthe person who can question the answers.\"\n        ― Theodore Schick Jr., in The_Skeptical_Inquirer, March/April, 1997"}
{"ok":false,"message":"\"... the educated person is not the person who can answer the questions, but\nthe person who can question the answers.\"\n        ― Theodore Schick Jr., in The_Skeptical_Inquirer, March/April, 1997"}
{"ok":false,"message":"\"... the educated person is not the person who can answer the questions, but\nthe person who can question the answers.\"\n        ― Theodore Schick Jr., in The_Skeptical_Inquirer, March/April, 1997"}
```

**expected:**

```
{"ok":false,"message":"\"... the educated person is not the person who can answer the questions, but\nthe person who can question the answers.\"\n        ― Theodore Schick Jr., in The_Skeptical_Inquirer, March/April, 1997"}

... other fortunes and not the same fortune.
```

**steps to reproduce:**

```
1. open https://fortune-cookie-monster.herokuapp.com/api/fortune/
2. note  "message" property
3. refresh a bunch, see "message" is pretty non-random.
```

**see attached:**
<img width="691" alt="screen shot 2016-10-04 at 8 15 43 pm" src="https://cloud.githubusercontent.com/assets/833793/19098029/56a9f456-8a6f-11e6-8b64-7c3b6e87b317.png">

**Comment by dmiddlecamp** [comment]
awesome, thanks!  Making a test so we don't regress on this!
